title: Test
description: Time team
social_link: Time team
social_username: Time team
github_repo: ''
github_username: ''
theme_color: ''
remote_theme: internet-de-france/athena
baseurl: /time_team
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
